### ISSUE TITLE
how do actions work?

### ISSUE THREAD

**Issue by dcsan** [lgrammel/js-agent#1]
ref https://twitter.com/lgrammel/status/1645840202055680013

if i use this framework to query openAI GPT model, how is output routed to a plugin vs just sending the openAI response?

since openAI doesn't know about these client side plugins, how do the two interact?

referencing:
- https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/action/ActionRegistry.ts
- https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/step/DynamicCompositeStep.ts
- https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/action/format/JsonActionFormat.ts

I see

```
You can perform the following actions using ${
      this.format.description
    }:

${this.describeActions()}

## RESPONSE FORMAT (ALWAYS USE THIS FORMAT)

Explain and describe your reasoning step by step.
Then use the following format to specify the action you want to perform next:

${this.format.format({
  action: "an action",
  param1: "a parameter value",
  param2: "another parameter value",
})}

You must always use exactly one action with the correct syntax per response.
Each response must precisely follow the action syntax.
```

so does openAI API respond with a block of text with `  action: "an action",` 
where 'an action' is something chatGPT would like executed

then client side the Action plugin will parse the openAI response and make any needed API calls requested from the action?

So looking at an example action 
https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/action/tool/summarize-webpage/SummarizeWebpageAction.ts
has

`    description = "Summarize a webpage considering a topic.",`

so openAI would be initialized with 

``
You can perform the following actions using ${
      this.format.description
    }:

${this.describeActions()}
```  =>

```
You can perform the following actions using [Summarize a webpage considering a topic]
```

still seems a bit messy but maybe I can run through and debug the intermediate steps.

**Comment by dcsan** [comment]
wow thanks for the detailed reply!  so this is how the system this side functions and handles calling the tools. this is code that I can probably follow.

But I'm still not clear how the decision to even include a tool is made, in terms of how the openAI model decides whether to include the tool's boilerplate in it's response?
eg when would it look up a wikipedia article, vs just replying based on what it knows?

Is this based on sending a pre-prompt/system prompt which is the tool description, and then just hoping the model chooses the tool on relevant occasions, and populates the tools boilerplate with exactly what it wants to lookup?

if this calling the tools code / processing the result is all done in your system, does that allow the openAI model to do anything with the tools output? Is it fed back to that agent somehow? eg

```
user: How many plays did Shakespeare write?
bot: (makes up a reply? or looks up in wikipedia?)
if it looks up, how can it form a sentence based on the tools query results? is that passed in as another 'turn' of the conversation?
```

**Comment by lgrammel** [comment]
Yes, the LLM chooses the tool based on the prompt and provides the arguments as well. The results are then fed into the prompt for the next step (iteration).

**Comment by lgrammel** [comment]
The agent runs a loop until it's done - it does not immediately respond to the user. The output that you are seeing in the console is just an example from observing the agent run. I plan to add examples of other environments as well.

You can find more details about loops here: 
* https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/step/Loop.ts
* https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/step/GenerateNextStepLoop.ts (this is the type of loop used by the wikipedia QA example)

On each iteration of a loop with GenerateNextStepLoop, a prompt is sent to the LLM. Results from previous action steps are included using the resultFormatter associated with the action:

* https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/prompt/RecentStepsPrompt.ts#L48

You can find the default result formatters in the actions (you can change them to your liking when you set up your agent), e.g.: https://github.com/lgrammel/gptagent.js/blob/main/packages/agent/src/tool/programmable-google-search-engine/ProgrammableGoogleSearchEngineTool.ts#L26
